version: 2.1

jobs:
  publish:
    docker:
    - image: python:3
    steps:
    - run:
        name: do nothing
        command: |
          echo "OK"

workflows:
  build:
    jobs:
    - publish:
        filters:
          branches:
            only: master
