name: Release

on:
  release:
    types: [released]

jobs:

  release:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload --non-interactive dist/*
